version: '3.8'
services:
  demo_app:
    container_name: demo_app
    build:
      context: ./demo_app
    image: demo_app
    volumes:
      - ./demo_app/nginx.conf:/etc/nginx/nginx.conf    
    ports:
      - 80:80  