version: '3.8'
services:
  app:
    container_name: demo_app
    build:
      context: ./app
    image: demo_app
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf    
    ports:
      - 80:80  